---
# Shared variables across all hosts (Workstations and Servers)
target_user: "{{ ansible_user_id if (ansible_user_id is defined and ansible_user_id != 'root') else (ansible_env.SUDO_USER | default(ansible_env.LOGNAME | default('user'))) }}"
user_home: "/home/{{ target_user }}"
user_bin: "{{ user_home }}/.local/bin"


# Chezmoi Dotfiles Repository URL
dotfiles_repo: "https://github.com/uarslandev/dotfiles.git"
