---
# Packages installed via DNF on Fedora Workstations
dnf_packages:
  - neovim
  - tmux
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - git
  - curl
  - wget
  - htop
  - btop
  - fastfetch
  - ripgrep
  - fd-find
  - fzf
  - jq
  - unzip
  - tar
  - gcc
  - make
  - python3-pip
  - nodejs
  - npm
  - util-linux-user
  - chezmoi
  - dconf

# Desktop GUI Applications installed via Flatpak
flatpak_apps:
  - dev.vencord.Vesktop
  - com.spotify.Client
  - md.obsidian.Obsidian

# Versions for standalone DevOps tools
devops_tool_versions:
  kubectl: "v1.31.1"
  helm: "v3.16.1"
  k9s: "v0.32.5"
  terraform: "1.9.6"
  kind: "v0.24.0"
  starship: "v1.21.1"
